version: "3.7"

services:
  teste-rabbitmq:
    image: rabbitmq:management
    container_name: teste-rabbitmq
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    env_file:
      - .env
    volumes:
      - rabbitmq:/usr/src/app/data

volumes:
  rabbitmq:
    name: teste-rabbitmq

networks:
  network:
    name: teste-network
